// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_BIVCgre_5RXYkA_hvoMICQJ_66GEh_0',
    appId: '1:568175721516:web:b8e042052b12ba2c942589',
    messagingSenderId: '568175721516',
    projectId: 'chat-app-a6faa',
    authDomain: 'chat-app-a6faa.firebaseapp.com',
    storageBucket: 'chat-app-a6faa.appspot.com',
    measurementId: 'G-TEBHN6NZZW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAh67fws6oLOVngQRK9uYFFFATAFRMPj0A',
    appId: '1:568175721516:android:44be718a8fa6472e942589',
    messagingSenderId: '568175721516',
    projectId: 'chat-app-a6faa',
    storageBucket: 'chat-app-a6faa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIemTSJ-b-owSEs2Vzo1QDo5xFsi-BaPE',
    appId: '1:568175721516:ios:4edc9f82a0c9c1c4942589',
    messagingSenderId: '568175721516',
    projectId: 'chat-app-a6faa',
    storageBucket: 'chat-app-a6faa.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIemTSJ-b-owSEs2Vzo1QDo5xFsi-BaPE',
    appId: '1:568175721516:ios:4edc9f82a0c9c1c4942589',
    messagingSenderId: '568175721516',
    projectId: 'chat-app-a6faa',
    storageBucket: 'chat-app-a6faa.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_BIVCgre_5RXYkA_hvoMICQJ_66GEh_0',
    appId: '1:568175721516:web:c8c5b86967ecd2b5942589',
    messagingSenderId: '568175721516',
    projectId: 'chat-app-a6faa',
    authDomain: 'chat-app-a6faa.firebaseapp.com',
    storageBucket: 'chat-app-a6faa.appspot.com',
    measurementId: 'G-TZBZ86WJ5V',
  );
}
